name: 'gas_prices_spa'
version: '1.0.0'
config-version: 2

profile: gas_prices_spa

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gas_prices_spa:
    marts:
      core:
        +materialized: table
      export:
        +materialized: view
    staging:
      +materialized: view

vars:
  start_date: "2025-01-01"
  end_date: "2025-01-31"

flags:
  use_colors: False
