gas_prices_spa:
  target: dev
  outputs:
    dev:
      dataset: dbt__gas_prices_spa
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      threads: 1
      type: bigquery
    prod:
      dataset: dbt__gas_prices_spa
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      threads: 1
      type: bigquery
