select
    cast(station_id as integer) station_id,
    date,
    {{ dbt_utils.surrogate_key(['station_id', 'date']) }} as price_id,
    safe_cast(replace(petrol_95E5, ',', '.') as numeric) as petrol_95E5,
    safe_cast(replace(petrol_95E5_premium, ',', '.') as numeric) as petrol_95E5_premium,
    safe_cast(replace(petrol_95E10, ',', '.') as numeric) as petrol_95E10,
    safe_cast(replace(petrol_98E5, ',', '.') as numeric) as petrol_98E5,
    safe_cast(replace(petrol_98E10, ',', '.') as numeric) as petrol_98E10,
    safe_cast(replace(diesel_A, ',', '.') as numeric) as diesel_A,
    safe_cast(replace(diesel_B, ',', '.') as numeric) as diesel_B,
    safe_cast(replace(diesel_premium, ',', '.') as numeric) as diesel_premium,
    safe_cast(replace(bioetanol, ',', '.') as numeric) as bioetanol,
    safe_cast(replace(biodiesel, ',', '.') as numeric) as biodiesel,
    safe_cast(replace(lpg, ',', '.') as numeric) as lpg,
    safe_cast(replace(cng, ',', '.') as numeric) as cng,
    safe_cast(replace(lng, ',', '.') as numeric) as lng,
    safe_cast(replace(hydrogen, ',', '.') as numeric) as hydrogen,

from {{ source('raw_data', 'prices') }}
